---
title: "R Notebook"
output: html_notebook
---


normalized_df$Rad.Ra <- func_outliers(normalized_df$Rad.Ra)
normalized_df$Pr.Axis.Ra <- func_outliers(normalized_df$Pr.Axis.Ra)
normalized_df$Max.L.Ra <- func_outliers(normalized_df$Max.L.Ra)
normalized_df$Sc.Var.Maxis <- func_outliers(normalized_df$Sc.Var.Maxis)
normalized_df$Sc.Var.maxis <- func_outliers(normalized_df$Sc.Var.maxis)
normalized_df$Skew.Maxis <- func_outliers(normalized_df$Skew.Maxis)
normalized_df$Skew.maxis <- func_outliers(normalized_df$Skew.maxis)
normalized_df$Kurt.maxis <- func_outliers(normalized_df$Kurt.maxis)

Try executing this chunk by clicking the *Run* button within the chunk or by placing your cursor inside it and pressing *Ctrl+Shift+Enter*. 

```{r}
plot(cars)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.